### ISSUE TITLE
[EOEPCA/IAM] Adapt existing User Management demo notebook

### ISSUE THREAD

**Issue by w-scho** [EOEPCA/iam#51]
It is foreseen to reuse the existing User Management demo notebook for the IAM BB.
This requires some testing of and several adaptation to the notebook.
A key difference between the old and the new configuration is that the old one used the master realm for everything, whereas the new one introduced a separate EOEPCA realm. This is basically foreseen, but not supported in full detail by the existing code.

**Comment by rconway** [comment]
@w-scho Description of outcomes?
