### ISSUE TITLE
[EOEPCA/IAM] Document APISIX route configuration

### ISSUE THREAD

**Issue by w-scho** [EOEPCA/iam#59]
Write a configuration guide or how-to for APISIX route configuration, covering all relevant cases (simple pass-through, authN only, authZ only, authN+authZ and combinations thereof).
Privide templates for the relevant cases.
This partially contributes to issue #12.

**Comment by rconway** [comment]
@w-scho Can you provide links to the outputs of this task

**Comment by w-scho** [comment]
The resulting Ingress Configuration Guide can be found here: https://eoepca.readthedocs.io/projects/iam/en/latest/admin/configuration/apisix/ingress-configuration/
The example files for the guide can be found here: https://github.com/EOEPCA/iam/tree/main/deployment/examples/apisix
Note that further planned amendments to the guide are documented here https://github.com/EOEPCA/iam/issues/69
