### ISSUE TITLE
[EOEPCA/IAM] Move OPA policies to separate repository

### ISSUE THREAD

**Issue by w-jfe** [EOEPCA/iam#62]
By now, OPA references a set of very general example policies provided with the Keykloak-OPA plugin.
It is expected that several EOEPCA-specific policies will evolve during the next few months. Therefore it makes sense to migrate to a new repository that should contain a copy of the example policies as well as new policies that are developed for EOEPCA.
The new repository may still be public, because it is meant as a standard set of policies for EOEPCA and also a template and starting point for policy sets of projects based on EOEPCA.

**Comment by w-scho** [comment]
The policy repo is now located here: https://github.com/EOEPCA/iam-policies/
OPAL points to the `main` branch of this repo.
